<?php

/**
 * Implements hook_entity_info().
 *
 * This is the fundamental description of the entity.
 *
 * It provides a single entity with a single bundle and without revision
 * support.
 */
function rooms_taxes_entity_info() {
  $info['rooms_taxes'] = array(
    // A human readable label to identify our tax entity.
    'label' => t('Rooms taxes basic Entity'),

    // The controller for our Entity, extending the Drupal core controller.
    'controller class' => 'EntityRoomsTaxesBasicController',

    // The table for this entity defined in hook_schema()
    'base table' => 'rooms_taxes',

    // Returns the uri elements of an entity.
    'uri callback' => 'rooms_taxes_uri',

    // IF fieldable == FALSE, we can't attach fields.
    'fieldable' => TRUE,

    // entity_keys tells the controller what database fields are used for key
    // functions. It is not required if we don't have bundles or revisions.
    // Here we do not support a revision, so that entity key is omitted.
    'entity keys' => array(
      // The 'id' (id here) is the unique id.
      'id' => 'id' ,
      // Bundle will be determined by the 'bundle_type' field.
      'bundle' => 'bundle_type',
    ),
    'bundle keys' => array(
      'bundle' => 'bundle_type',
    ),

    // FALSE disables caching. Caching functionality is handled by Drupal core.
    'static cache' => TRUE,

    // Bundles are alternative groups of fields or configuration
    // associated with a base entity type.
    'bundles' => array(
      'incidentals_bundle' => array(
        'label' => 'Incidentals taxes bundle',
        // 'admin' key is used by the Field UI to provide field and
        // display UI pages.
        'admin' => array(
          'path' => 'admin/structure/rooms_taxes/manage',
          'access arguments' => array('administer rooms_taxes entities'),
        ),
      ),
    ),
    // View modes allow entities to be displayed differently based on context.
    // As a demonstration we'll support "Tweaky", but we could have and support
    // multiple display modes.
    'view modes' => array(
      'tweaky' => array(
        'label' => t('Tweaky'),
        'custom settings' => FALSE,
      ),
    ),
      
    // Entity API needs to know about your module for the views integration to work
    'module' => 'rooms_taxes',
  );

  return $info;
}

/**
 * Fetch a basic object.
 *
 * This function ends up being a shim between the menu system and
 * rooms_taxes_load_multiple().
 *
 * This function gets its name from the menu system's wildcard
 * naming conventions. For example, /path/%wildcard would end
 * up calling wildcard_load(%wildcard value). In our case defining
 * the path: examples/entity_example/basic/%rooms_taxes in
 * hook_menu() tells Drupal to call rooms_taxes_load().
 *
 * @param int $id
 *   Integer specifying the basic entity id.
 * @param bool $reset
 *   A boolean indicating that the internal cache should be reset.
 *
 * @return object
 *   A fully-loaded $basic object or FALSE if it cannot be loaded.
 *
 * @see rooms_taxes_load_multiple()
 * @see entity_example_menu()
 */
function rooms_taxes_load($id = NULL, $reset = FALSE) {
  $ids = (isset($id) ? array($id) : array());
  $basic = rooms_taxes_load_multiple($ids, array(), $reset);
  return $basic ? reset($basic) : FALSE;
}

/**
 * Loads multiple basic entities.
 *
 * We only need to pass this request along to entity_load(), which
 * will in turn call the load() method of our entity controller class.
 */
function rooms_taxes_load_multiple($ids = FALSE, $conditions = array(), $reset = FALSE) {
  return entity_load('rooms_taxes', $ids, $conditions, $reset);
}

/**
 * Implements the uri callback.
 */
function rooms_taxes_uri($basic) {
  return array(
    'path' => 'rooms_taxes/' . $basic->id,
  );
}

/**
 * Implements hook_menu().
 */
function rooms_taxes_menu() {
  
  
  $items['hs'] = array(
    'title' => 'Edit',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('rooms_taxes_hs_form'),
    'access arguments' => array('edit any rooms_taxes entity'),
    'type' => MENU_LOCAL_TASK,
  );
  
  
  $items['rooms_taxes'] = array(
    'title' => 'Rooms Taxes Entity Info page',
    'page callback' => 'rooms_taxes_info_page',
    'access arguments' => array('view any rooms_taxes entity'),
  );

  // This provides a place for Field API to hang its own
  // interface and has to be the same as what was defined
  // in basic_entity_info() above.
  $items['admin/structure/rooms_taxes/manage'] = array(
    'title' => 'Rooms taxes',
    'page callback' => 'rooms_taxes_list_entities',
    'access arguments' => array('administer rooms_taxes entities'),
  );

  // Add example entities.
  $items['admin/structure/rooms_taxes/manage/add'] = array(
    'title' => 'Add a Rooms Taxes Basic Entity',
    'page callback' => 'rooms_taxes_add',
    'access arguments' => array('create rooms_taxes entities'),
    'type' => MENU_LOCAL_ACTION,
  );

  // List of all rooms_taxes entities.
  $items['admin/structure/rooms_taxes/manage/list'] = array(
    'title' => 'List',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );

  // The page to view our entities - needs to follow what
  // is defined in basic_uri and will use load_basic to retrieve
  // the necessary entity info.
  $items['rooms_taxes/%rooms_taxes'] = array(
    'title callback' => 'rooms_taxes_title',
    'title arguments' => array(1),
    'page callback' => 'rooms_taxes_view',
    'page arguments' => array(1),
    'access arguments' => array('view any rooms_taxes entity'),
  );

  // 'View' tab for an individual entity page.
  $items['rooms_taxes/%rooms_taxes/view'] = array(
    'title' => 'View',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );

  // 'Edit' tab for an individual entity page.
  $items['rooms_taxes/%rooms_taxes/edit'] = array(
    'title' => 'Edit',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('rooms_taxes_form', 1),
    'access arguments' => array('edit any rooms_taxes entity'),
    'type' => MENU_LOCAL_TASK,
  );

  // Add example entities.
//  $items['rooms_taxes/add'] = array(
//    'title' => 'Add an Rooms Taxes Basic Entity',
//    'page callback' => 'rooms_taxes_add',
//    'access arguments' => array('create rooms_taxes entities'),
//  );
  

  return $items;
}

/**
 * Basic information for the page.
 */
function rooms_taxes_info_page() {
  $content['preface'] = array(
    '#type' => 'item',
    '#markup' => t('The Rooms Taxes info page.'),
  );
  if (user_access('administer rooms_taxes entities')) {
    $content['preface']['#markup'] = t('You can administer these and add fields and change the view !link.',
      array('!link' => l(t('here'), 'admin/structure/rooms_taxes/manage'))
    );
  }
  $content['table'] = rooms_taxes_list_entities();

  return $content;
}

/**
 * Implements hook_permission().
 */
function rooms_taxes_permission() {
  $permissions = array(
    'administer rooms_taxes entities' => array(
      'title' => t('Administer rooms_taxes entities'),
    ),
    'view any rooms_taxes entity' => array(
      'title' => t('View any Rooms Taxes Basic entity'),
    ),
    'edit any rooms_taxes entity' => array(
      'title' => t('Edit any Rooms Taxes Basic entity'),
    ),
    'create rooms_taxes entities' => array(
      'title' => t('Create Rooms Taxes Basic Entities'),
    ),
  );
  return $permissions;
}

/**
 * Returns a render array with all rooms_taxes entities.
 *
 * In this basic example we know that there won't be many entities,
 * so we'll just load them all for display. See pager_example.module
 * to implement a pager. Most implementations would probably do this
 * with the contrib Entity API module, or a view using views module,
 * but we avoid using non-core features in the Examples project.
 *
 * @see pager_example.module
 */
function rooms_taxes_list_entities() {
  $content = array();
  // Load all of our entities.
  $entities = rooms_taxes_load_multiple();
  if (!empty($entities)) {
    foreach ($entities as $entity) {
      
      field_extra_fields_get_display('node', $node->type, $view_mode);
      // Create tabular rows for our entities.
      $rows[] = array(
        'data' => array(
          'id' => $entity->id,
          'title' => l($entity->title, 'rooms_taxes/' . $entity->id),
          
          'name' => $entity->name,
          'description' => $entity->description,
          'rate' => $entity->rate,  
          'target' => $entity->target,
            
          //'bundle' => $entity->bundle_type,
        ),
      );
    }
    // Put our entities into a themed table. See theme_table() for details.
    $content['entity_table'] = array(
      '#theme' => 'table',
      '#rows' => $rows,
      //'#header' => array(t('ID'), t('Tax title'), t('Bundle')),
      '#header' => array(t('ID'), t('Tax title'), t('Name'), t('Description'), t('Rate'), t('Target(s)')),  
    );
  }
  else {
    // There were no entities. Tell the user.
    $content[] = array(
      '#type' => 'item',
      '#markup' => t('No rooms_taxes entities currently exist.'),
    );
  }
  return $content;
}

/**
 * Callback for a page title when this entity is displayed.
 */
function rooms_taxes_title($entity) {
  return t('Entity Rooms Taxes (title=@title)', array('@title' => $entity->title));
}

/**
 * Menu callback to display an entity.
 *
 * As we load the entity for display, we're responsible for invoking a number
 * of hooks in their proper order.
 *
 * @see hook_entity_prepare_view()
 * @see hook_entity_view()
 * @see hook_entity_view_alter()
 */
function rooms_taxes_view($entity, $view_mode = 'tweaky') {
  // Our entity type, for convenience.
  $entity_type = 'rooms_taxes';
  // Start setting up the content.
  $entity->content = array(
    '#view_mode' => $view_mode,
  );
  // Build fields content - this is where the Field API really comes in to play.
  // The task has very little code here because it all gets taken care of by
  // field module.
  // field_attach_prepare_view() lets the fields load any data they need
  // before viewing.
  field_attach_prepare_view($entity_type, array($entity->id => $entity),
    $view_mode);
  // We call entity_prepare_view() so it can invoke hook_entity_prepare_view()
  // for us.
  entity_prepare_view($entity_type, array($entity->id => $entity));
  // Now field_attach_view() generates the content for the fields.
  $entity->content += field_attach_view($entity_type, $entity, $view_mode);

  // OK, Field API done, now we can set up some of our own data.
  $entity->content['timestamp'] = array(
    '#type' => 'item',
    '#title' => t('Created/changed date'),
    '#markup' => format_date($entity->timestamp),
  );
  $entity->content['title'] = array(
    '#type' => 'item',
    '#title' => t('Tax title'),
    '#markup' => $entity->title,
  );
  $entity->content['name'] = array(
    '#type' => 'item',
    '#title' => t('Tax name'),
    '#markup' => $entity->name,
  );
  $entity->content['description'] = array(
    '#type' => 'item',
    '#title' => t('Tax description'),
    '#markup' => $entity->description,
  );
  $entity->content['rate'] = array(
    '#type' => 'item',
    '#title' => t('Tax rate'),
    '#markup' => $entity->rate,
  );
  $entity->content['target'] = array(
    '#type' => 'item',
    '#title' => t('Tax target(s)'),
    '#markup' => $entity->target,
  );
  $entity->content['status'] = array(
    '#type' => 'item',
    '#title' => t('Tax status'),
    '#markup' => $entity->status,
  );



  // Now to invoke some hooks. We need the language code for
  // hook_entity_view(), so let's get that.
  global $language;
  $langcode = $language->language;
  // And now invoke hook_entity_view().
  module_invoke_all('entity_view', $entity, $entity_type, $view_mode, $langcode);
  
  // Now invoke hook_entity_view_alter().
  ////drupal_alter(array('rooms_taxes_view', 'entity_view'), $entity->content, $entity_type);

  // And finally return the content.
  return $entity->content;
}

/**
 * Implements hook_field_extra_fields().
 *
 * This exposes the "extra fields" (usually properties that can be configured
 * as if they were fields) of the entity as pseudo-fields
 * so that they get handled by the Entity and Field core functionality.
 * Node titles get treated in a similar manner.
 */
function rooms_taxes_field_extra_fields() {
  $form_elements['title'] = array(
    'label' => t('Title'),
    'description' => t('Title (an extra form field)'),
    'weight' => -5,
  );
  $display_elements['timestamp'] = array(
    'label' => t('Timestamp'),
    'description' => t('Creation/changing date (an extra display field)'),
    'weight' => 0,
  );
  $display_elements['title'] = array(
    'label' => t('Tax title'),
    'description' => t('Just like a simple title, but trying to point out that it is a separate property'),
    'weight' => 0,
  );

  // Since we have only one bundle type, we'll just provide the extra_fields
  // for it here.
  $extra_fields['rooms_taxes']['incidentals_bundle']['form'] = $form_elements;
  $extra_fields['rooms_taxes']['incidentals_bundle']['display'] = $display_elements;

  return $extra_fields;
}

/**
 * Provides a wrapper on the edit form to add a new entity.
 */
function rooms_taxes_add() {
  // Create a basic entity structure to be used and passed to the validation
  // and submission functions.
  $entity = entity_get_controller('rooms_taxes')->create();
  return drupal_get_form('rooms_taxes_form', $entity);
}

/**
 * Form function to create an rooms_taxes entity.
 *
 * The pattern is:
 * - Set up the form for the data that is specific to your
 *   entity: the columns of your base table.
 * - Call on the Field API to pull in the form elements
 *   for fields attached to the entity.
 */
function rooms_taxes_form($form, &$form_state, $entity) {
  
  $form['title'] = array(
    '#type' => 'textfield',
    '#title' => t('Title'),
    '#required' => TRUE,
    '#default_value' => $entity->title,
  );

  $form['name'] = array(
    '#type' => 'textfield',
    '#title' => t('Machine name'),
    '#required' => TRUE,
    '#default_value' => $entity->name,
  );
  $form['description'] = array(
    '#type' => 'textfield',
    '#title' => t('Description'),
    //'#required' => TRUE,
    '#default_value' => $entity->description,
  );
  $form['rate'] = array(
    '#type' => 'textfield',
    '#title' => t('Rate'),
    '#required' => TRUE,
    '#default_value' => $entity->rate,
  );
  $form['target'] = array(
    '#type' => 'textfield',
    '#title' => t('Target object(s)'),
    '#required' => TRUE,
    '#default_value' => $entity->target,
  );
  $form['status'] = array(
    '#type' => 'checkbox',
    '#title' => t('Status'),
    //'#required' => TRUE,
    '#default_value' => $entity->status,
  );
  
  
  
  $form['basic_entity'] = array(
    '#type' => 'value',
    '#value' => $entity,
  );

  field_attach_form('rooms_taxes', $entity, $form, $form_state);

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save'),
    '#weight' => 100,
  );
  $form['delete'] = array(
    '#type' => 'submit',
    '#value' => t('Delete'),
    '#submit' => array('rooms_taxes_edit_delete'),
    '#weight' => 200,
  );

  return $form;
}


/**
 * Validation handler for rooms_taxes_add_form form.
 *
 * We pass things straight through to the Field API to handle validation
 * of the attached fields.
 */
function rooms_taxes_form_validate($form, &$form_state) {
  field_attach_form_validate('rooms_taxes', $form_state['values']['basic_entity'], $form, $form_state);
}


/**
 * Form submit handler: Submits basic_add_form information.
 */
function rooms_taxes_form_submit($form, &$form_state) {
  $entity = $form_state['values']['basic_entity'];
  
  $entity->title = $form_state['values']['title'];
  $entity->name = $form_state['values']['name'];
  $entity->description = $form_state['values']['description'];
  $entity->rate = $form_state['values']['rate'];
  $entity->target = $form_state['values']['target'];
  $entity->status = $form_state['values']['status'];
  
  
  field_attach_submit('rooms_taxes', $entity, $form, $form_state);
  $entity = rooms_taxes_save($entity);
  $form_state['redirect'] = 'rooms_taxes/' . $entity->id;
}

/**
 * Form deletion handler.
 *
 * @todo: 'Are you sure?' message.
 */
function rooms_taxes_edit_delete($form, &$form_state) {
  $entity = $form_state['values']['basic_entity'];
  rooms_taxes_delete($entity);
  drupal_set_message(t('The entity %title (ID %id) has been deleted',
    array('%title' => $entity->title, '%id' => $entity->id))
  );
  $form_state['redirect'] = 'rooms_taxes';
}

/**
 * We save the entity by calling the controller.
 */
function rooms_taxes_save(&$entity) {
  return entity_get_controller('rooms_taxes')->save($entity);
}

/**
 * Use the controller to delete the entity.
 */
function rooms_taxes_delete($entity) {
  entity_get_controller('rooms_taxes')->delete($entity);
}

/**
 * EntityExampleBasicControllerInterface definition.
 *
 * We create an interface here because anyone could come along and
 * use hook_entity_info_alter() to change our controller class.
 * We want to let them know what methods our class needs in order
 * to function with the rest of the module, so here's a handy list.
 *
 * @see hook_entity_info_alter()
 */
interface EntityRoomsTaxesBasicControllerInterface
  extends EntityAPIControllerInterface {
  //extends DrupalEntityControllerInterface {

  /**
   * Create an entity.
   */
  public function create(array $values = array());

  /**
   * Save an entity.
   *
   * @param object $entity
   *   The entity to save.
   */
  public function save($entity);

  /**
   * Delete an entity.
   *
   * @param object $entity
   *   The entity to delete.
   */
  public function delete($entity);

}

/**
 * EntityExampleBasicController extends DrupalDefaultEntityController.
 *
 * Our subclass of DrupalDefaultEntityController lets us add a few
 * important create, update, and delete methods.
 */
class EntityRoomsTaxesBasicController
  extends EntityAPIController
  ////extends DrupalDefaultEntityController
  implements EntityRoomsTaxesBasicControllerInterface {

  /**
   * Create and return a new rooms_taxes entity.
   */
  public function create(array $values = array()) {
    $entity = new stdClass();
    $entity->type = 'rooms_taxes';
    $entity->id = 0;
    $entity->bundle_type = 'incidentals_bundle';
    
    $entity->title = '';
    $entity->name = '';
    $entity->description = '';
    $entity->rate = '';
    $entity->target = '';
    $entity->status = 1;
    
    return $entity;
  }

  /**
   * Saves the custom fields using drupal_write_record().
   */
  public function save($entity) {
    
    $entity->timestamp = time();
    
    // Invoke hook_entity_presave().
    module_invoke_all('entity_presave', $entity, 'rooms_taxes');
    // The 'primary_keys' argument determines whether this will be an insert
    // or an update. So if the entity already has an ID, we'll specify
    // id as the key.
    $primary_keys = $entity->id ? 'id' : array();
    // Write out the entity record.
    drupal_write_record('rooms_taxes', $entity, $primary_keys);
    // We're going to invoke either hook_entity_update() or
    // hook_entity_insert(), depending on whether or not this is a
    // new entity. We'll just store the name of hook_entity_insert()
    // and change it if we need to.
    $invocation = 'entity_insert';
    // Now we need to either insert or update the fields which are
    // attached to this entity. We use the same primary_keys logic
    // to determine whether to update or insert, and which hook we
    // need to invoke.
    if (empty($primary_keys)) {
      field_attach_insert('rooms_taxes', $entity);
    }
    else {
      field_attach_update('rooms_taxes', $entity);
      $invocation = 'entity_update';
    }
    // Invoke either hook_entity_update() or hook_entity_insert().
    module_invoke_all($invocation, $entity, 'rooms_taxes');
    return $entity;
  }

  /**
   * Delete a single entity.
   *
   * Really a convenience function for deleteMultiple().
   */
  public function delete($entity) {
    $this->deleteMultiple(array($entity));
  }

  /**
   * Delete one or more rooms_taxes entities.
   *
   * Deletion is unfortunately not supported in the base
   * DrupalDefaultEntityController class.
   *
   * @param array $entities
   *   An array of entity IDs or a single numeric ID.
   */
  public function deleteMultiple($entities) {
    $ids = array();
    if (!empty($entities)) {
      $transaction = db_transaction();
      try {
        foreach ($entities as $entity) {
          // Invoke hook_entity_delete().
          module_invoke_all('entity_delete', $entity, 'rooms_taxes');
          field_attach_delete('rooms_taxes', $entity);
          $ids[] = $entity->id;
        }
        db_delete('rooms_taxes')
          ->condition('id', $ids, 'IN')
          ->execute();
      }
      catch (Exception $e) {
        $transaction->rollback();
        watchdog_exception('rooms_taxes', $e);
        throw $e;
      }
    }
  }
}


/**
 * Implements hook_commerce_price_component_type_info()
 * 
 * Should define price components for all user defined hotel taxes.
 * 
 * @return type
 */
function rooms_taxes_commerce_price_component_type_info() {
  
  $components = array();
  
  // Example of a resulting array with rooms taxes cmponents.
  $stub = array(
    'rooms_tax|sales_tax' => array(
      'title' => t('Sales tax'),
      'weight' => -10,
    ),
    'rooms_tax|alcohol_tax' => array(
      'title' => t('Alcohol tax'),
      'weight' => -10,
    ),
  );
  $components = $stub;
  
  
  return $components;
}

/**
 * 
 */
function rooms_taxes_getHotelTaxes($order_id, $category_tids = array()) {
    
    $order = commerce_order_load($order_id);
    $hotel_nid = $order->field_diy_hotel_nid['und'][0]['value'];
    
    $taxes = array(
        'rooms_tax|sales_tax' => array(
            'name' => 'rooms_tax|sales_tax|110',
            'title' => 'Sales tax',
            'rate' => 0.20,
            'active' => TRUE,
            ),
        'rooms_tax|alcohol_tax' => array(
            'hotel_tax_name' => 'rooms_tax|alcohol_tax|110',
            'title' => 'Alcohol tax',
            'rate' => 0.15,
            'active' => TRUE,
            ),
    );
    
    return $taxes;
}




function rooms_taxes_hs_form() {
  //$modules = _hsdemo_page_shared();

//  if (!in_array('hs_taxonomy', $modules)) {
//    $form['not'] = array(
//      '#markup' => t('Not installed.'),
//    );
//    return $form;
//  }

  $default = array(
      1,4,
      '2',
      2,6 
  );

  $form['example_2'] = array(
    '#type' => 'hierarchical_select',
    '#title' => t('My car park'),
    '#description' => t('At least when I win the lottery … twice.'),
    '#required' => TRUE,
    '#default_value' => $default, //unserialize(HSDEMO_TAXONOMY_EXAMPLE_2_DEFAULT),
    '#config' => array(
      'module' => 'hs_taxonomy',
      'params' => array(
        'vid'                        => HSDEMO_TAXONOMY_EXAMPLE_2_VID,
        'exclude_tid'                => NULL,
        'root_term'                  => NULL,
        'entity_count_for_node_type' => NULL,
      ),
      'save_lineage'    => 1,
      'enforce_deepest' => 0,
      'entity_count'    => 0,
      'require_entity'  => 0,
      'level_labels' => array(
        'status' => 0,
      ),
      'dropbox' => array(
        'status'   => 1,
        'title'    => t('Car park'),
        'limit'    => 0,
        'reset_hs' => 0,
      ),
      'editability' => array(
        'status' => 0,
      ),
      'resizable' => 1,
      'render_flat_select' => 0,
    ),
    '#weight' => 4,
  );


$form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save'),
    '#weight' => 100,
  );
  
  
  return $form;
}



  
/**
 * Form submit handler: Submits basic_add_form information.
 */
function rooms_taxes_hs_form_submit($form, &$form_state) {
  dpm($form_state['values']);
  //$form_state['redirect'] = 'rooms_taxes/' . $entity->id;
}